# Generated by Django 2.0.7 on 2018-07-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ourbooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookId', models.CharField(max_length=14)),
                ('author', models.CharField(max_length=200)),
                ('readingdate', models.DateField(auto_now_add=True)),
                ('category', models.CharField(max_length=14)),
                ('booktitle', models.CharField(max_length=100)),
                ('presentation', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('statusflag', models.CharField(max_length=5)),
            ],
        ),
    ]
