# Generated by Django 2.0.7 on 2018-07-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180729_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetingId', models.CharField(max_length=14)),
                ('bookId', models.CharField(max_length=14)),
                ('meetingdate', models.CharField(max_length=14)),
                ('attendants', models.CharField(max_length=100)),
                ('meetingtitle', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('photopath', models.CharField(max_length=200)),
                ('content', models.TextField(default='')),
            ],
        ),
    ]
