# Generated by Django 2.0.7 on 2018-08-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='lastorder',
            field=models.TextField(default=''),
        ),
    ]
