# Generated by Django 2.0.7 on 2018-08-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_meeting_lastorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryCode', models.CharField(max_length=14)),
                ('categoryName', models.CharField(max_length=30)),
            ],
        ),
    ]
