# Generated by Django 2.0.7 on 2018-08-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourbooks',
            name='imgindex',
            field=models.CharField(default='', max_length=5),
        ),
    ]
