# Generated by Django 2.0.7 on 2018-08-06 07:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ourbooks_imgindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('writer', models.CharField(max_length=30)),
                ('created', models.CharField(max_length=30)),
            ],
        ),
    ]
