# Generated by Django 2.0.7 on 2018-08-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_reading_bookid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourbooks',
            name='id',
        ),
        migrations.AlterField(
            model_name='ourbooks',
            name='bookId',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reading',
            name='bookId',
            field=models.ForeignKey(on_delete='', to='main.Ourbooks'),
        ),
    ]
