# Generated by Django 2.0.7 on 2018-09-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180808_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='sentence',
            fields=[
                ('senId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('senContent', models.TextField(default='')),
                ('senWriter', models.CharField(max_length=30)),
                ('created', models.CharField(max_length=30)),
                ('bookId', models.ForeignKey(on_delete='', to='main.Ourbooks')),
            ],
        ),
        migrations.AlterField(
            model_name='reading',
            name='readId',
            field=models.CharField(default='1', max_length=30, primary_key=True, serialize=False),
        ),
    ]
