# Generated by Django 2.0.7 on 2018-09-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180902_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='starScore',
            fields=[
                ('scoreId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('scoreComment', models.TextField(default='')),
                ('scoreStar', models.CharField(max_length=30)),
                ('scoreWriter', models.CharField(max_length=30)),
                ('created', models.CharField(max_length=30)),
                ('bookId', models.ForeignKey(on_delete='', to='main.Ourbooks')),
            ],
        ),
    ]
