# Generated by Django 2.0.7 on 2018-09-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_ourbooks_discuss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
