# Generated by Django 2.0.7 on 2018-09-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180909_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishbooks',
            fields=[
                ('wishId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('register', models.CharField(max_length=100)),
                ('wishbooktitle', models.CharField(max_length=100)),
                ('ourbookflag', models.CharField(max_length=5)),
                ('reason', models.TextField(default='')),
                ('created', models.CharField(max_length=30)),
                ('bookId', models.ForeignKey(on_delete='', to='main.Ourbooks')),
            ],
        ),
    ]
