# Generated by Django 2.0.7 on 2018-09-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_wishbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishbooks',
            name='bookId',
            field=models.CharField(max_length=100),
        ),
    ]
