# Generated by Django 2.0.7 on 2018-09-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20180919_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishbooks',
            name='imgindex',
            field=models.CharField(default='', max_length=30),
        ),
    ]
