# Generated by Django 2.0.7 on 2018-12-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20181022_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='petercatSentence',
            fields=[
                ('senId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=100)),
                ('senContent', models.TextField(default='')),
                ('senWriter', models.CharField(max_length=30)),
                ('register', models.CharField(max_length=30)),
                ('created', models.CharField(max_length=30)),
            ],
        ),
    ]
