# Generated by Django 2.0.7 on 2018-12-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_petercatsentence'),
    ]

    operations = [
        migrations.CreateModel(
            name='petercatMenu',
            fields=[
                ('menuId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('engname', models.TextField(default='')),
                ('zhname', models.TextField(default='')),
                ('specialgubun', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('korname', models.ForeignKey(on_delete='', to='main.Reading')),
            ],
        ),
    ]
