# Generated by Django 2.0.7 on 2018-12-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_petercatmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='petercatmenu',
            name='price',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='petercatmenu',
            name='useYn',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='petercatmenu',
            name='category',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='petercatmenu',
            name='korname',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='petercatmenu',
            name='specialgubun',
            field=models.CharField(default='', max_length=30),
        ),
    ]
