# Generated by Django 2.0.7 on 2018-12-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20181226_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='petercatBook',
            fields=[
                ('bookId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('booktitle', models.TextField(default='')),
                ('meeingdate', models.TextField(default='')),
                ('meeingtime', models.TextField(default='')),
            ],
        ),
    ]
