# Generated by Django 2.0.7 on 2018-12-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_petercatbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='petercatbook',
            name='meetingtitle',
            field=models.CharField(default='', max_length=30),
        ),
    ]
