# Generated by Django 2.0.7 on 2018-12-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_petercatbook_meetingcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='petercatbook',
            name='imgindex',
            field=models.CharField(default='', max_length=30),
        ),
    ]
